// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type PacketMutations struct {
	Create *Packet `json:"create"`
	Delete string  `json:"delete"`
	Update *Packet `json:"update"`
}

type PacketQuery struct {
	Packets []*Packet `json:"packets"`
	Packet  *Packet   `json:"packet"`
}

type ProviderMutations struct {
	Create *Provider `json:"create"`
	Delete string    `json:"delete"`
	Update *Provider `json:"update"`
}

type ProviderQuery struct {
	Providers []*Provider `json:"providers"`
	Provider  *Provider   `json:"provider"`
}

type Query struct {
}

type UserMutations struct {
	Register       *UserToken `json:"register"`
	Delete         string     `json:"delete"`
	Update         string     `json:"update"`
	Login          *UserToken `json:"login"`
	Buy            string     `json:"buy"`
	CancelPacket   string     `json:"cancelPacket"`
	Choose         string     `json:"choose"`
	CancelProvider string     `json:"cancelProvider"`
}

type UserQuery struct {
	Users []*User `json:"users"`
	User  *User   `json:"user"`
}

type UserToken struct {
	Message string `json:"message"`
	Token   string `json:"token"`
}
