package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.46

import (
	"context"
	"fmt"
	"myapp/graph/generated"
	"myapp/model"
)

// Users is the resolver for the users field.
func (r *mutationResolver) Users(ctx context.Context) (*model.UserMutations, error) {
	return &model.UserMutations{}, nil
}

// Providers is the resolver for the providers field.
func (r *mutationResolver) Providers(ctx context.Context) (*model.ProviderMutations, error) {
	return &model.ProviderMutations{}, nil
}

// Packet is the resolver for the packet field.
func (r *mutationResolver) Packet(ctx context.Context) (*model.PacketMutations, error) {
	return &model.PacketMutations{}, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) (*model.UserQuery, error) {
	return &model.UserQuery{}, nil
}

// Providers is the resolver for the providers field.
func (r *queryResolver) Providers(ctx context.Context) (*model.ProviderQuery, error) {
	return &model.ProviderQuery{}, nil
}

// Packet is the resolver for the packet field.
func (r *queryResolver) Packet(ctx context.Context) (*model.PacketQuery, error) {
	return &model.PacketQuery{}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *mutationResolver) Package(ctx context.Context) (*model.PacketMutations, error) {
	panic(fmt.Errorf("not implemented: Package - package"))
}
func (r *queryResolver) Package(ctx context.Context) (*model.PacketQuery, error) {
	panic(fmt.Errorf("not implemented: Package - package"))
}
